version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    env_file:
      - ./.env.dev
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/dockelib/postgresql/data/
    environment:
      - POSTGRES_USER=cost
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=cost_db

volumes:
  postgres_data:

